version: '3'
services:
  postgresql:
    image: postgres:11.7-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: i_have_i_need_development
      POSTGRES_USER: dev_local_user
      POSTGRES_PASSWORD: password

  app-redis:
    container_name: "app-redis"
    image: redis:4.0.11-alpine
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass g71kLdC1QvEzDlV6