default: &default
  hackney:
    support_email: "help@beacon.support"
    copyright_notice: "© 2020 Hackney Council"
    logo_path: "hackney.svg"

  camden:
    support_email: "help@beacon.support"
    copyright_notice: "© 2020 Camden Council"
    logo_path: "camden.svg"

development:
  <<: *default

production:
  <<: *default
