  demo:
    name: "Demo Council"
    support_email: "help@beacon.support"
    copyright_notice: "© 2020 Demo Council"
    logo_path: "camden.svg"
    privacy_link: "https://www.camden.gov.uk/data-protection-privacy-and-cookies"
    default_from_address: "CHANGE_ME@example.com"

  hackney:
    name: "Hackney Council"
    support_email: "help@beacon.support"
    copyright_notice: "© 2020 Hackney Council"
    logo_path: "hackney.svg"
    privacy_link: "https://www.hackney.gov.uk/privacy"
    default_from_address: "CHANGE_ME@example.com"

  camden:
    name: "Camden Council"
    support_email: "help@beacon.support"
    copyright_notice: "© 2020 Camden Council"
    logo_path: "camden.svg"
    privacy_link: "#"
    default_from_address: "CHANGE_ME@example.com"

development:
  <<: *default

production:
  <<: *default
