default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://localhost/i_have_i_need_development
  # username: dev_local_user
  # password: password

test:
  <<: *default
  url: postgresql://localhost/i_have_i_need_test
  # username: test_local_user
  # password: password

production:
  <<: *default
  database: i_have_i_need_production
  username: i_have_i_need
  password: <%= ENV['I_HAVE_I_NEED_DATABASE_PASSWORD'] %>
