name: Ruby Test Env
# As opposed to the ci env used before on the Ruby action

on:
  push:
    branches: [ richard_ci_testing_test_env ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.7-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.7
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Setup database
      env:
        RAILS_ENV: ci
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ci_db_test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        SECRET_KEY_BASE: fcd3d03a727ad50a19d2a89555bc9683
      run: |
        bundle exec rails db:setup
    - name: Run tests
      env:
        RAILS_ENV: ci
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ci_db_test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        SECRET_KEY_BASE: fcd3d03a727ad50a19d2a89555bc9683
      run: |
        echo "pre spec RAILS_ENV: $RAILS_ENV"
        bundle exec rails spec
