name: Ruby

on:
  push:
    branches: [ richard_ci_testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.7-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.7
    - name: Build with bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Setup database
      env:
        RAILS_ENV: ci
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ci_db_test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        COUNCIL: demo
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
